sudo: required

language: cpp
compiler: gcc
script:
  - bash ./scripts/build.sh
  - bash ./scripts/test.sh

after_success:
  - pip install --user cpp-coveralls
  - coveralls -e deps -e tests -e example -E "build/CMakeFiles/3*" -E "build/CMakeFiles/*_tests*" --gcov-options '\-lp'
