sudo: required

language: cpp
compiler: gcc
script:
  - bash ./scripts/build.sh
  - bash ./scripts/test.sh

after_success:
  - pip install --user cpp-coveralls
  - coveralls -e deps -e tests -e example -e build/CMakeFiles --gcov-options '\-lp'
