sudo: required

language: cpp
compiler: gcc
script:
  - bash ./scripts/build.sh
  - bash ./scripts/test.sh

after_success:
  - pip install --user cpp-coveralls
  - coveralls -r . --gcov-options '\-lp' -e deps -e build -e example -e tests -e scripts
